### ISSUE TITLE
Release on conda

### ISSUE THREAD

**Issue by chrisjsewell** [greschd/aiida-tools#3]
Hey @greschd :wave:  just copying this here, in case you don't notice on Slack.
I wanted to get some of the aiida plugins on conda (to make it easier to build the quantum mobile, for the common workflows, etc), this is something I can mainly do on my own.
For `aiida-siesta`, basically I need to get` aiida-siesta` <- `aiida-optimize` <- `aiida-tools` <- `fsc.export` :sweat_smile:
But I hit an initial problem with `fsc.export`; that it does not have a license bundled in the source code, and does not specify an apache version: https://github.com/conda-forge/staged-recipes/pull/19518
I also couldn't find where the actual source code is located for this (https://pypi.org/project/fsc.export/)?
Is this something you could help me with cheers?

For easy reference:
- https://github.com/siesta-project/aiida_siesta_plugin/blob/develop/setup.json
- https://github.com/greschd/aiida-optimize/blob/develop/setup.json
- https://github.com/greschd/aiida-tools/blob/master/setup.py

**Comment by greschd** [comment]
Hi Chris,

You're right, I didn't see it on Slack 😅

First off, the source for `fsc.export` is here: https://github.com/FrescolinoGroup/pyexport, I guess the license got missing from the Manifest, it's here: https://github.com/FrescolinoGroup/pyexport/blob/master/AUTHORS

Anyway, that code is from my "young and naive" days.. it doesn't really do enough to warrant an extra dependency. So if you prefer, I could also update `aiida-tools` to not use it.

**Comment by chrisjsewell** [comment]
> Anyway, that code is from my "young and naive" days.. it doesn't really do enough to warrant an extra dependency. So if you prefer, I could also update aiida-tools to not use it.

Thanks for the quick reply!

Oh to be young and naieve 😆 

Yeh, my leaning is indeed usually to remove these dependencies, that add very minimal code.
Too many encounters with "dependency hells" haha

**Comment by greschd** [comment]
Voilà: https://pypi.org/project/aiida-tools/0.4.0/

Let me know if you encounter any issues.. since this package doesn't have any unit tests, I just ran it against the `aiida-optimize` tests.

**Comment by chrisjsewell** [comment]
cheers!
