### ISSUE TITLE
Move to aiidaplugins org and 0.4.0 broke

### ISSUE THREAD

**Issue by chrisjsewell** [greschd/aiida-tools#4]
Hey, @greschd, would you consider moving this to https://github.com/aiidaplugins?
I'd like to move more plugins here, that are currently owned by single users, just so its easy to maintain them consistently.

One reason I mention this, is that v0.4.0 is broken, because `_check_workchain_step.py` still imports `fsc` 😅 
Then also, ideally, there would be a release without `fsc`, that still allowed for aiida v1.x, so I can use it on conda for aiida-siesta, etc, which have not updated yet to 2.x

**Comment by greschd** [comment]
>  because `_check_workchain_step.py` still imports `fsc` 😅 

Ah crap, guess I rushed that release a bit too much.

> that still allowed for aiida v1.x

guess that's just a matter of changing it in the requirements

> would you consider moving this to https://github.com/aiidaplugins

Sure, why not.. but I wonder if the more effective approach wouldn't be to deprecate this repo, and copy the parts (basically only `process_inputs`) that `aiida-optimize` needs there.

**Comment by chrisjsewell** [comment]
> but I wonder if the more effective approach wouldn't be to deprecate this repo, and copy the parts (basically only process_inputs) that aiida-optimize needs there.

I'm all for that 😄 (ideally also releasing that for aiida-core 1.x)

**Comment by chrisjsewell** [comment]
> guess that's just a matter of changing it in the requirements

👍

**Comment by greschd** [comment]
> ideally also releasing that for aiida-core 1.x

Eh, I'm not all that into backporting those changes.. how about a hybrid approach where we release an `aiida-tools` version `0.4.1` with AiiDA 1.x and 2.x support and `fsc` removed, and `aiida-optimize` with `aiida-tools` removed for AiiDA 2.x?

**Comment by chrisjsewell** [comment]
Sure ting 👍

**Comment by greschd** [comment]
https://pypi.org/project/aiida-optimize/1.0.1/
https://pypi.org/project/aiida-tools/0.4.1/

**Comment by chrisjsewell** [comment]
cheers!

**Comment by greschd** [comment]
hope it works better this time around :sweat_smile:
